### ISSUE TITLE
Try the github version of scan-build py 

### ISSUE THREAD

**Issue by Xazax-hun** [Ericsson/clang#100]
It might not have the escaping problem that makes some of the projects failed to be analyzed

**Comment by gerazo** [comment]
It has become totally incompatible. Our scripts have to be rewritten.

We got tons of these:
analyze-cc: Internal error.
Traceback (most recent call last):
  File "/mnt/storage/xtu_service/clang_build/checker_env/local/lib/python2.7/site-packages/libscanbuild/__init__.py", line 121, in wrapper
    return function(*args, **kwargs)
  File "/mnt/storage/xtu_service/clang_build/checker_env/local/lib/python2.7/site-packages/libscanbuild/__init__.py", line 159, in wrapper
    parameters = json.loads(os.environ[ENVIRONMENT_KEY])
  File "/mnt/storage/xtu_service/clang_build/checker_env/lib/python2.7/UserDict.py", line 40, in __getitem__
    raise KeyError(key)
KeyError: 'INTERCEPT_BUILD'
analyze-cc: Please run this command again and turn on verbose mode (add '-vvvv' as argument).

**Comment by whisperity** [comment]
How are you invoking the main function of `libscanbuild/init.py`? It looks like something gets messy there, but the worst is that we can't see what's on the **top** of the stack.

**Comment by gerazo** [comment]
Our scripts call analyze-cc which calls into the lib. The whole behaviour is governed by passing environment variables and they seems to be changed. See https://github.com/dkrupp/clang/blob/ctu-master/tools/xtu-build-new/xtu-analyze.py

**Comment by dkrupp** [comment]
try to generate a new buildlog.json using the intercept-build command in scan-build.py

**Comment by gerazo** [comment]
Turns out, intercept build just uses double escaping. If we do the same, everything will be fine. So turning a bad buildlog.json into a good one is simple as:
`sed -i 's/\\\(.\)/\\\\\\\1/g' buildlog.json`
