### ISSUE TITLE
"external function declared with incompatible types" problem in postgresql

### ISSUE THREAD

**Issue by szepet** [Ericsson/clang#101]
analyze: INFO: /mnt/storage/xtu_service/projects/postgresql/build/src/backend/access/index/indexam.c:533:1: error: external function 'index_getnext' declared with incompatible types in different translation units ('HeapTuple (IndexScanDesc, ScanDirection)' (aka 'struct HeapTupleData *(struct IndexScanDescData *, enum ScanDirection)') vs. 'HeapTuple (IndexScanDesc, ScanDirection)' (aka 'struct HeapTupleData *(struct IndexScanDescData *, enum ScanDirection)'))
analyze: INFO: index_getnext(IndexScanDesc scan, ScanDirection direction)
analyze: INFO: ^
analyze: INFO: /mnt/storage/xtu_service/projects/postgresql/build/src/include/access/genam.h:150:18: note: declared here with type 'HeapTuple (IndexScanDesc, ScanDirection)' (aka 'struct HeapTupleData *(struct IndexScanDescData *, enum ScanDirection)')
analyze: INFO: extern HeapTuple index_getnext(IndexScanDesc scan, ScanDirection direction);
analyze: INFO:                  ^

**Comment by gerazo** [comment]
This problem was gone from postgresql.
