### ISSUE TITLE
would it be better to identify ast files with the object file name

### ISSUE THREAD

**Issue by dkrupp** [Ericsson/clang#113]
if a C file is compiled with different compilaton options into different objects, still one AST dump is created per C file, which is overwritten. Probably it would be better to used the .o files' path to identify the AST dump.

**Comment by whisperity** [comment]
Could it be a better idea to somehow hash the build command that was used in building and use it as an identifier attached to the AST dump?

How would I say that if I'm analyzing translation unit `A` with a configuration environment of `C`, that when I need to import TU `B` and it has versions `C` and `D` (two different compilation options) which one to load?

What if the build system itself creates multiple objects **in the same place**, overwriting each other in different compilation steps? While not common with _CMake_ projects, I think the Linux kernel uses such technique.

**Comment by martong** [comment]
@dkrupp, @whisperity is it still a relevant issue? This is rather a CodeChecker issue, isn't it (was) ?

**Comment by martong** [comment]
Should be handled in CodeChecker level.
