### ISSUE TITLE
add ctu-build function to scan-build

### ISSUE THREAD

**Issue by dkrupp** [Ericsson/clang#116]

**Comment by gerazo** [comment]
See https://github.com/rizsotto/scan-build/issues/83

**Comment by gerazo** [comment]
Function complete with all known bugs fixed. Still no tests.

**Comment by gerazo** [comment]
First PR with tests is in: https://github.com/rizsotto/scan-build/pull/84

**Comment by dkrupp** [comment]
implemented here:
https://github.com/rizsotto/scan-build/pull/87/files
