### ISSUE TITLE
Issue with using CTU analysis

### ISSUE THREAD

**Issue by Davidbrcz** [Ericsson/clang#119]
Hello,

I'm trying to use the CTU analysis but I'm struggling on Ubuntu 16.04. I'm following [this](https://github.com/fuchsia-mirror/docs/blob/master/ctu_analysis.md) and [this](https://github.com/Ericsson/clang/blob/ctu-master/tools/xtu-build-new/readme.md).

I'm able to compile clang/ctu-os branch (with LLVM checkouted at the commit ff14b9ebc7a06ecd170651ecfeb4e4a26bcd4b31). ctu-build.py runs fine but ctu-analyze.py fails with the following output

```
~/code/llvm_for_ericsson/llvm_src/tools/clang/tools/ctu-analysis/ctu-analyze.py  -v -b compile_commands.json --clang-path /usr/local_ericsson/bin/ --output-format=plist
INFO:root:CTU uses clang dir: /usr/local_ericsson/bin
INFO:root:CTU uses analyze-cc dir: <taken from PATH>
INFO:root:analyze-cc -g -o CMakeFiles/demo-csu.dir/a.cpp.o -c /home/david/code/tests/test_ctu_csa/src/a.cpp
INFO:root:analyze-cc -g -o CMakeFiles/demo-csu.dir/b.cpp.o -c /home/david/code/tests/test_ctu_csa/src/b.cpp
INFO:root:Compile status: failed
INFO:root:/bin/sh: 1: analyze-cc: not found

INFO:root:Compile status: failed
INFO:root:/bin/sh: 1: analyze-cc: not found

INFO:root:Removing directory /home/david/code/tests/test_ctu_csa/bin/.ctu-out because it contains no reports

```

Running ack on clang source folder looking for a analyze-cc did not yield any result. There are two binaries (c++-analyzer and ccc-analyzer) in libexec but giving that path to --analyze-cc-path did not help.

When trying to compile clang/ctu-master (also with LLVM checkouted at ff14b9...), the compilation fails with the following error 

```
/home/david/code/llvm_for_ericsson/llvm_src/tools/clang/lib/AST/ItaniumMangle.cpp: In member function ‘void {anonymous}::CXXNameMangler::mangleFloat(const llvm::APFloat&)’:
/home/david/code/llvm_for_ericsson/llvm_src/tools/clang/lib/AST/ItaniumMangle.cpp:998:5: error: ‘integerPart’ is not a member of ‘llvm’
     llvm::integerPart hexDigit
     ^
/home/david/code/llvm_for_ericsson/llvm_src/tools/clang/lib/AST/ItaniumMangle.cpp:1000:5: error: ‘hexDigit’ was not declared in this scope
     hexDigit >>= (digitBitIndex % llvm::integerPartWidth);
     ^
/home/david/code/llvm_for_ericsson/llvm_src/tools/clang/lib/AST/ItaniumMangle.cpp:1000:35: error: ‘integerPartWidth’ is not a member of ‘llvm’
     hexDigit >>= (digitBitIndex % llvm::integerPartWidth);
                                   ^
```

Thanks !
David

**Comment by whisperity** [comment]
`analyze-cc` shall be found in `clang/tools/scan-build-py/bin`, where `clang` is the repository root of the `llvm-clang` project. It's [also available in our repository](https://github.com/Ericsson/clang/blob/master/tools/scan-build-py/bin/analyze-cc).

The document you are using *MIGHT* be outdated... it is using absolute SHAs to identify commits, which may or may not be proper by now. I haven't the environment to check this right now.

For the second issue, I'm invoking @Xazax-hun and @dkrupp here. I'm not very well versed in on the internals of this patch. :slightly_smiling_face:

**Comment by Xazax-hun** [comment]
For the second part, sorry for the inconvenience!
The ff14b9ebc7a06ecd170651ecfeb4e4a26bcd4b31 commit is for the ctu-os branch, which is less feature complete branch that is being open sourced right now. Since we are focusing on the open sourcing effort, we did not really have time to rebase the ctu-master on the ToT recently.

For ctu-master branch lets try an llvm checkut from Feb. 27. We will add a notice to the branch next time we rebase it with a compatible llvm checkout.

**Comment by Davidbrcz** [comment]
Thanks for the answers, it works fine. 

As far as I can see, your work deals with free functions. There is no support for interprocedual analysis of member function ?

**Comment by gerazo** [comment]
Hi David, It is supposed to work with member functions as well. We also test such functionality with the following:
https://github.com/Ericsson/clang/blob/ctu-os/test/Analysis/ctu-main.cpp
https://github.com/Ericsson/clang/blob/ctu-os/test/Analysis/Inputs/ctu-chain.cpp
https://github.com/Ericsson/clang/blob/ctu-os/test/Analysis/Inputs/ctu-other.cpp

**Comment by Davidbrcz** [comment]
Indeed it does. CSA did not find a bug in my demo project but I have successfully imported a member function.

I'll use it in my own tool ;-). Do you have a roadmap somewhere ?

**Comment by Xazax-hun** [comment]
We do not have a roadmap to upstream this, since it is also up to the community to get this accepted into the mainline clang, but we would like to make it production ready in this fork with C++ by the end of this year. 

The open sourcing effort can be tracked here: https://reviews.llvm.org/D30691

Note that, that is only a minimal patch, and do not contain all the functionality that is available in this fork.

**Comment by Xazax-hun** [comment]
It looks like this works. Thank you for the feedback. I just rebased the ctu-master and added a note to the corresponding llvm commit on the wiki.
