### ISSUE TITLE
Xerces: Support importing UnresolvedMemberExpr and UnresolvedLookupExpr

### ISSUE THREAD

**Issue by szepet** [Ericsson/clang#134]
AST nodes UnresolvedMemberExpr and UnresolvedLookupExpr importing are not supported but an experimental version already can be found here: https://github.com/haoNoQ/clang/blob/summary-ipa-draft/lib/AST/ASTImporter.cpp#L7499

**Comment by Xazax-hun** [comment]
Should be fixed by: #159
