### ISSUE TITLE
BitCoin: Support importing PackExpansion

### ISSUE THREAD

**Issue by szepet** [Ericsson/clang#136]
AST node PackExpansion importing is not supported but an experimental version already can be found here: https://github.com/haoNoQ/clang/blob/summary-ipa-draft/lib/AST/ASTImporter.cpp#L7683

**Comment by Xazax-hun** [comment]
We should first focus on finishing most of C++98, and schedule C++11 features after C++98 is mostly ok.

**Comment by gerazo** [comment]
https://reviews.llvm.org/D39247

**Comment by dkrupp** [comment]
please add Astmerge based testcase to the phabricator patch. add bruno lopes and spyffe (sean calanan) as revewiers

**Comment by gerazo** [comment]
New tests and reviewers were added: https://reviews.llvm.org/D39247

**Comment by gerazo** [comment]
Went into mainline clang: https://reviews.llvm.org/D39247
