### ISSUE TITLE
clang-func-mapping uses 'CTU' and 'XTU' interchangibly

### ISSUE THREAD

**Issue by whisperity** [Ericsson/clang#155]
In the help of `clang-func-mapping`, the argument `--xtu-dir` says `ctu` in its help, also a default invocation says `Exactly one `**`CTU`**` dir should be provided`.

I used the `ctu-master` branch.

**Comment by dkrupp** [comment]
rewrite all xtu to ctu in ctu-clang5 and ctu-master branches. update the xtu-build.py and xtu-analyze.py scripts. make sure that they work, and memory profiling and coverage measurement works.

**Comment by martong** [comment]
@dkrupp, @Xazax-hun 
Is it still relevant in ctu-clang6?

**Comment by Xazax-hun** [comment]
No
