### ISSUE TITLE
xtu-analyze gives error

### ISSUE THREAD

**Issue by dkrupp** [Ericsson/clang#167]
./clang_build/clang/tools/xtu-build-new/xtu-analyze.py -b ./projects/tinyxml2/build/buildlog.json -p ./.xtu-test -o xtu-out
Traceback (most recent call last):
  File "./clang_build/clang/tools/xtu-build-new/xtu-analyze.py", line 193, in <module>
    buildgraph_file = open(bg_file, 'r')
IOError: [Errno 2] No such file or directory: './.xtu-test/build_dependency.json'

**Comment by Xazax-hun** [comment]
Fixed: https://github.com/Ericsson/clang/commit/e34d1760e1b19b0f56a5dff02098b4839fc5d4ab
