### ISSUE TITLE
Add asserts and bail out where error was changed to warning

### ISSUE THREAD

**Issue by dkrupp** [Ericsson/clang#172]
In this commit errors were changed to warning:
https://github.com/Ericsson/clang/commit/4b38271e218709c82a843ba340e3cdbabbdfd8f2

This is dangerous, because the AstImporter will create faulty ASTs.
To fix this:
* Add asserts to every such place where these warnings are emmitted
* Retrun from the importer with a proper error code and without changing the `to AstContext`

**Comment by Xazax-hun** [comment]
This is not a good approach, the test will fail if we implement this.
