### ISSUE TITLE
Unnamed structs import crashes on windows

### ISSUE THREAD

**Issue by dkrupp** [Ericsson/clang#195]
https://reviews.llvm.org/D30876

check why

**Comment by szepet** [comment]
Has not been able to reproduce. Email sent to the buildbot owner. Has not responded yet.

**Comment by dkrupp** [comment]
send a mail about the problem to the cfe-dev list

**Comment by Xazax-hun** [comment]
No mail was sent. Please send it to the mailing list ASAP.

**Comment by dkrupp** [comment]
please update the phabricator patch to master clang and retry the commit

**Comment by martong** [comment]
D30876 looks OK, now.
