### ISSUE TITLE
analyze-build generates incompatible exernalfnmap.txt

### ISSUE THREAD

**Issue by dkrupp** [Ericsson/clang#200]
Please fix on the ctu-os branch and then @Xazax-hun  can update the patch:
https://reviews.llvm.org/D30691

tools/scan-build-py/libscanbuild/analyze.py
--
535 | There is a incompatibility between this scan-build (analyze-build actually) implementation and new lib/CrossTU library.CrossTranslationUnitContext::loadExternalAST(StringRef LookupName, StringRef CrossTUDir, StringRef IndexName)expects the externalFnMap.txt to be in"functionName astFilename" format.however currently we generate here"functionName@arch astFilename" lines.One possible fix could be to create one externalFnMap.txt indexes per arch<collect-dir>/ast/x86_64/externalFnMap.txt<collect-dir>/ast/ppc64/externalFnMap.txtetc.and call clang analyze with the architecture specific map directory: e.g. ctu-dir=<collect-dir>/ast/x86_64This would then work if the "to-be-analyzed" source-code is cross-compiled into multiple architectures.Would be useful to add a test-case too to check if the map file and ctu-dir content generated by analyze-build is compatible.
585 | Maybe we could use the full target-triple for distinguishing the AST binaries, not only the architecture part. The sys part for example is probably important too and a "win32" AST may not be compatible with a "linux" AST.

**Comment by gerazo** [comment]
Here is the solution: https://github.com/Ericsson/clang/pull/201
