### ISSUE TITLE
Cherry-pick new issue hash calculation

### ISSUE THREAD

**Issue by Xazax-hun** [Ericsson/clang#206]
A fix to calculate issue hashes was accepted upstream. Cherry-pick this into ctu-clang5 branch.

**Comment by whisperity** [comment]
@Xazax-Hun Can you link the phabricator patch? I'm interested in this!

**Comment by Xazax-hun** [comment]
https://reviews.llvm.org/rL316900

**Comment by Xazax-hun** [comment]
Done: https://github.com/Ericsson/clang/commit/6040a46d9683bf9f0cb7a83b3446dbf844e45a6f
