### ISSUE TITLE
Can not build clang-ctu under VS2017 on Win7 64bit

### ISSUE THREAD

**Issue by zhangxiaobin2** [Ericsson/clang#227]
when I build clang-ctu with llvm5.0, one of clang-ctu projects which named "clangStaticAnalyzerFrontend" with target type library cannot compile successful.

It show me:
39>------ Build started: Project: clangStaticAnalyzerFrontend, Configuration: Debug x64 ------
39>AnalysisConsumer.cpp
39>E:\svn\developer_codes\llvm-5.0.1_ctu\llvm-release_50\tools\clang\lib\StaticAnalyzer\Frontend\AnalysisConsumer.cpp(52): fatal error C1083: **Cannot open include file: 'sys/file.h'**: No such file or directory
39>Done building project "clangStaticAnalyzerFrontend.vcxproj" -- FAILED.
========== Build: 38 succeeded, 1 failed, 6 up-to-date, 0 skipped ==========

Look into the file "AnalysisConsumer.cpp", at the head of the file where specify the include file, it has two line:
#include <sys/file.h>
#include <unistd.h>

I search these two files on google, **it looks like those files are defined on "Linux" system.**
Does it means clang-ctu only can be compiled under Linux system?

I think clang-ctu should be compiled under Windows system like the "llvm-mirror/clang".
Can you fix this issue?

Thanks

**Comment by martong** [comment]
Hi, I think these headers are just leftover from a previous commit where the guys (@dkrupp  and @Xazax-hun ) had been using mangled names instead of USRs to identify the functions.
We could just simply remove those lines:
```
//#include <fcntl.h>
//#include <sys/file.h>
//#include <unistd.h>
```

If that is the case, I'll create a PR in a few minutes.

**Comment by zhangxiaobin2** [comment]
It still have this issue in the "ctu-master" branch, do you forgot to modify it ?
