### ISSUE TITLE
function "realpath" undefined on win platform when I use VS2017 to compile "ctu-clang5"

### ISSUE THREAD

**Issue by zhangxiaobin2** [Ericsson/clang#231]
function "realpath" undefined on win platform when I use VS2017 to compile "ctu-clang5".
57>------ Build started: Project: clang-func-mapping, Configuration: Debug x64 ------
57>ClangFnMapGen.cpp
57>E:\svn\developer_codes\llvm-5.0.1_ctu\llvm-release_50\tools\clang\tools\clang-func-mapping\ClangFnMapGen.cpp(82): **error C3861: 'realpath': identifier not found**
57>Done building project "clang-func-mapping.vcxproj" -- FAILED.

At the file " tools / clang-func-mapping / ClangFnMapGen.cpp ":
73         if (CurrentFileName.empty()) { 
74           StringRef SMgrName = 
75               SM.getFileEntryForID(SM.getMainFileID())->getName(); 
76           char *Path = **realpath**(SMgrName.str().c_str(), nullptr); 
77           CurrentFileName = Path; 
78           free(Path); 
79         } 

"realpath" is a function which is defined on linux system, we could not find the definition on the windows platform.

 I think "realpath" should be replaced by "PathCanonicalize" or "PathCchCanonicalize" or other function which has the similar mean on windows platform.

What I said is right ?

**Comment by Xazax-hun** [comment]
Should be fixed in https://github.com/Ericsson/clang/commit/deff29383499f3a5386c0f56743355f1b44a385c
