### ISSUE TITLE
Assignment to *this fails

### ISSUE THREAD

**Issue by bruntib** [Ericsson/clang#242]
When using CTU, then assignment to `*this` crashes Clang during analysis. Consider the following example:
```cpp
// myclass.h
class C
{
public:
  void f();
}

// myclass.cpp
void C::f()
{
  *this = C();
}

// main.cpp
#include "myclass.h"
int main()
{
  C c;
  c.f();
}
```
The error manifests in IteratorChecker (which is not in the Clang code base yet by the way). The context looks like this:
```cpp
void IteratorChecker::checkPostCall(const CallEvent &Call, CheckerContext &C) const {
  const auto *Func = dyn_cast_or_null<FunctionDecl>(Call.getDecl());
  if (Func->isOverloadedOperator()) {
    const auto Op = Func->getOverloadedOperator();
    if (isAssignmentOperator(Op)) {
      const auto *InstCall = dyn_cast<CXXInstanceCall>(&Call);
      // =====> This call fails because InstCall is a nullptr. <=====
      InstCall->getCXXThisVal();
    }
  }
}
```

**Comment by dkrupp** [comment]
I think the AST of the functiondecl of f differs.
the left one is the correct where in *this = C(); the "=" is CXXOperatorCallExpr
![astdump](https://user-images.githubusercontent.com/8030953/35057114-dd96901a-fbab-11e7-9620-1c2539a85115.png)
