### ISSUE TITLE
ASTImport does not support AST node CXXTypeidExpr

### ISSUE THREAD

**Issue by martong** [Ericsson/clang#248]

**Comment by Xazax-hun** [comment]
This node should be easy to import, very few constructor parameters: https://clang.llvm.org/doxygen/classclang_1_1CXXTypeidExpr.html

**Comment by Xazax-hun** [comment]
I added an implementation here: https://reviews.llvm.org/D42335

**Comment by martong** [comment]
Fixed by #269
