### ISSUE TITLE
Wrong order of nodes in namespace

### ISSUE THREAD

**Issue by martong** [Ericsson/clang#276]
```
        template<class T>
        class Base { int a; };
        class Derived : Base<Derived> {};
        void declToImport(Derived&);
```

Original `DeclContext` of the TranslationUnitDecl:
```
template <class T> class Base {
    int a;
};
class Derived : Base<Derived> {
};
void declToImport(Derived &);
```

Imported `DeclContext`:
```
class Derived : Base<Derived> {
};
template <class T> class Base {
    int a;
};
void declToImport(Derived &);
```

This is true for any namespaces, in this example the global namespace.

Can cause anomalies in lookup related logic, or where declaration order does matter.

**Comment by Xazax-hun** [comment]
Did you encounter issues caused by this?

**Comment by martong** [comment]
@Xazax-hun Could not find any direct relation to any crash yet.
Still on a long term structural equivalence should return false in the above cases.
See https://github.com/Ericsson/clang/blob/ctu-clang5/unittests/AST/StructuralEquivalenceTest.cpp#L162

**Comment by martong** [comment]
This does not cause any problem, because during structural eq of namespaces we do not check that order.
