### ISSUE TITLE
When importing a constructor declaration, its declaration context is not C++ record declaration

### ISSUE THREAD

**Issue by martong** [Ericsson/clang#278]
Top of stack trace:

clang-5.0: /home/edmbalo/ctu/llvm/include/llvm/Support/Casting.h:255: typename llvm::cast_retty<X, Y*>::ret_type llvm::cast(Y*) [with X = clang::CXXRecordDecl; Y = clang::DeclContext; typename llvm::cast_retty<X, Y*>::ret_type = clang::CXXRecordDecl*]: Assertion `isa(Val) && "cast() argument of incompatible type!"' failed.
#0 0x00007fbacec45fd9 llvm::sys::PrintStackTrace(llvm::raw_ostream&) /home/edmbalo/ctu/llvm/lib/Support/Unix/Signals.inc:398:0
#1 0x00007fbacec4606a PrintStackTraceSignalHandler(void*) /home/edmbalo/ctu/llvm/lib/Support/Unix/Signals.inc:462:0
#2 0x00007fbacec444b0 llvm::sys::RunSignalHandlers() /home/edmbalo/ctu/llvm/lib/Support/Signals.cpp:49:0
#3 0x00007fbacec45971 SignalHandler(int) /home/edmbalo/ctu/llvm/lib/Support/Unix/Signals.inc:252:0
#4 0x00007fbacb577cb0 (/lib/x86_64-linux-gnu/libc.so.6+0x36cb0)
#5 0x00007fbacb577c37 gsignal /build/eglibc-oGUzwX/eglibc-2.19/signal/../nptl/sysdeps/unix/sysv/linux/raise.c:56:0
#6 0x00007fbacb57b028 abort /build/eglibc-oGUzwX/eglibc-2.19/stdlib/abort.c:91:0
#7 0x00007fbacb570bf6 __assert_fail_base /build/eglibc-oGUzwX/eglibc-2.19/assert/assert.c:92:0
#8 0x00007fbacb570ca2 (/lib/x86_64-linux-gnu/libc.so.6+0x2fca2)
#9 0x00007fbac71a93ea llvm::cast_retty<clang::CXXRecordDecl, clang::DeclContext*>::ret_type llvm::cast<clang::CXXRecordDecl, clang::DeclContext>(clang::DeclContext*) /home/edmbalo/ctu/llvm/include/llvm/Support/Casting.h:257:0
#10 0x00007fbac71bfae8 clang::ASTNodeImporter::VisitFunctionDecl(clang::FunctionDecl*) /home/edmbalo/ctu/llvm/tools/clang/lib/AST/ASTImporter.cpp:2447:0
#11 0x00007fbac71c06e9 clang::ASTNodeImporter::VisitCXXMethodDecl(clang::CXXMethodDecl*) /home/edmbalo/ctu/llvm/tools/clang/lib/AST/ASTImporter.cpp:2574:0
#12 0x00007fbac71c070f clang::ASTNodeImporter::VisitCXXConstructorDecl(clang::CXXConstructorDecl*) /home/edmbalo/ctu/llvm/tools/clang/lib/AST/ASTImporter.cpp:2578:0

**Comment by baloghadamsoftware** [comment]
Top of stack trace:

clang-5.0: /home/edmbalo/ctu/llvm/include/llvm/Support/Casting.h:255: typename llvm::cast_retty<X, Y*>::ret_type llvm::cast(Y*) [with X = clang::CXXRecordDecl; Y = clang::DeclContext; typename llvm::cast_retty<X, Y*>::ret_type = clang::CXXRecordDecl*]: Assertion `isa<X>(Val) && "cast<Ty>() argument of incompatible type!"' failed.
#0 0x00007fbacec45fd9 llvm::sys::PrintStackTrace(llvm::raw_ostream&) /home/edmbalo/ctu/llvm/lib/Support/Unix/Signals.inc:398:0
#1 0x00007fbacec4606a PrintStackTraceSignalHandler(void*) /home/edmbalo/ctu/llvm/lib/Support/Unix/Signals.inc:462:0
#2 0x00007fbacec444b0 llvm::sys::RunSignalHandlers() /home/edmbalo/ctu/llvm/lib/Support/Signals.cpp:49:0
#3 0x00007fbacec45971 SignalHandler(int) /home/edmbalo/ctu/llvm/lib/Support/Unix/Signals.inc:252:0
#4 0x00007fbacb577cb0 (/lib/x86_64-linux-gnu/libc.so.6+0x36cb0)
#5 0x00007fbacb577c37 gsignal /build/eglibc-oGUzwX/eglibc-2.19/signal/../nptl/sysdeps/unix/sysv/linux/raise.c:56:0
#6 0x00007fbacb57b028 abort /build/eglibc-oGUzwX/eglibc-2.19/stdlib/abort.c:91:0
#7 0x00007fbacb570bf6 __assert_fail_base /build/eglibc-oGUzwX/eglibc-2.19/assert/assert.c:92:0
#8 0x00007fbacb570ca2 (/lib/x86_64-linux-gnu/libc.so.6+0x2fca2)
#9 0x00007fbac71a93ea llvm::cast_retty<clang::CXXRecordDecl, clang::DeclContext*>::ret_type llvm::cast<clang::CXXRecordDecl, clang::DeclContext>(clang::DeclContext*) /home/edmbalo/ctu/llvm/include/llvm/Support/Casting.h:257:0
#10 0x00007fbac71bfae8 clang::ASTNodeImporter::VisitFunctionDecl(clang::FunctionDecl*) /home/edmbalo/ctu/llvm/tools/clang/lib/AST/ASTImporter.cpp:2447:0
#11 0x00007fbac71c06e9 clang::ASTNodeImporter::VisitCXXMethodDecl(clang::CXXMethodDecl*) /home/edmbalo/ctu/llvm/tools/clang/lib/AST/ASTImporter.cpp:2574:0
#12 0x00007fbac71c070f clang::ASTNodeImporter::VisitCXXConstructorDecl(clang::CXXConstructorDecl*) /home/edmbalo/ctu/llvm/tools/clang/lib/AST/ASTImporter.cpp:2578:0

**Comment by baloghadamsoftware** [comment]
Minimal example:

[first.c.txt](https://github.com/Ericsson/clang/files/1703278/first.c.txt)
[first.h.txt](https://github.com/Ericsson/clang/files/1703279/first.h.txt)
[second.cpp.txt](https://github.com/Ericsson/clang/files/1703280/second.cpp.txt)
[second.h.txt](https://github.com/Ericsson/clang/files/1703281/second.h.txt)
[third.cpp.txt](https://github.com/Ericsson/clang/files/1703282/third.cpp.txt)

CodeChecker log -o compile.json -b "gcc -c --std=c99 first.c && g++ -c second.cpp && g++ -c third.cpp"
CodeChecker analyze --ctu -o report compile.json --analyzers clangsa

**Comment by baloghadamsoftware** [comment]
The crash happens the following way:
1. Function in C++ source file invokes function in C file
2. `ASTImporter` imports function from C file which uses variadic arguments
3. Structure `__va_list_tag`  is imported which was created by `ASTContext` as `RecordDecl`.
4. Function in C++ source file invokes function in C++ file
5. `ASTImporter` imports function from C++ file which declares variable of type  `__builtin_va_list`
6. `CXXConstructExpr` is imported, therefore the definition of the constructor is also imported
7. Structure `__va_list_tag`  (created by `ASTContext` as `CXXRecordDecl`) is **not** imported because `RecordDecl` with the same name exists.
8. Implicitly generated `CXXConstructorDecl` cannot be successfully imported because `RecordDecl` cannot be casted to `CXXRecordDecl`.

**Comment by baloghadamsoftware** [comment]
#287
