### ISSUE TITLE
create c-reduce script to get minimal examples

### ISSUE THREAD

**Issue by dkrupp** [Ericsson/clang#288]
1st phase
only reduce the root source file.

start out from the result of the clang debug script
https://github.com/Ericsson/clang/wiki#reproducing-a-ctu-crashes

start out from the bitcoin crashes.

create the script here
https://github.com/Ericsson/codechecker/tree/master/scripts/debug_tools

**Comment by szepet** [comment]
https://github.com/Ericsson/codechecker/pull/1378
