### ISSUE TITLE
in CTU mode there are many ``has incompatible definitions in different translation units`` warnings

### ISSUE THREAD

**Issue by dkrupp** [Ericsson/clang#289]
During xerces analysis in CTU mode we have 13000 warnings

[MEDIUM] XercesXPath.hpp:42:25: type 'xercesc_3_1::XercesNodeTest' has incompatible definitions in different translation units [ericsson.utility.WarningToReportConverter]

**Comment by whisperity** [comment]
It might be worthy to note that Xerces, in particular, has a compilation database that contains duplicated build actions. At least from what I remember...

**Comment by Xazax-hun** [comment]
The number of warnings should be reduced significantly after applying https://github.com/Ericsson/clang/pull/297
There are still some warnings though.

**Comment by dkrupp** [comment]
@dkrupp to  retest this.

**Comment by dkrupp** [comment]
there are still a few remaining on xerces please recheck.

**Comment by Xazax-hun** [comment]
These warnings/errors are disappeared from Xerces. I will add the corresponding options on the CI to make sure never bring these back.
