### ISSUE TITLE
Assertion compare(**Y, **X) && "Not a total order!"

### ISSUE THREAD

**Issue by dkrupp** [Ericsson/clang#428]
https://reviews.llvm.org/rL336269

**Comment by gerazo** [comment]
So the main problem is this assert: `Assertion `compare(**Y, **X) && "Not a total order!"' failed.`
This is not only specific to this patch as it is invoked in the latest redis release version as well. `lib/StaticAnalyzer/Core/PathDiagnostic.cpp:compare()` function is not doing a total ordering. This is a general problem on this function. It also uses `compareCrossTUSourceLocs()` and `comparePath()` so any of these comparisons can be responsible for not doing a total ordering. Even in case of partly bogus or missing data, ordering should be total especially when thinking on future changes in data interpretation.

**Comment by dkrupp** [comment]
can be reproduced on redis

**Comment by dkrupp** [comment]
cannot reproduce with clang7
