### ISSUE TITLE
create additional opensource patches for Error handling on ASTImporter

### ISSUE THREAD

**Issue by dkrupp** [Ericsson/clang#509]

**Comment by dkrupp** [comment]
D53818 [ASTImporter] Changed use of Import to Import_New in ASTImporter.
D53751 [ASTImporter] Added Import functions for transition to new API.
D53757 [ASTImporter] Changed use of Import to Import_New in ASTNodeImporter.

and we need some more.

**Comment by dkrupp** [comment]
fix the failing test ton MacOS and reopen the phabricator patch https://reviews.llvm.org/D53818

**Comment by dkrupp** [comment]
we are waiting for #556 to finish. we should finish this before clang 8 is forked.

**Comment by balazske** [comment]
I think #620 is the newer issue for the same thing. This can be closed.

**Comment by balazske** [comment]
It looks like that this issue is about upstreaming #518 .

**Comment by martong** [comment]
https://reviews.llvm.org/D61438
