### ISSUE TITLE
rebase clang7 branch with error handling

### ISSUE THREAD

**Issue by dkrupp** [Ericsson/clang#514]

**Comment by dkrupp** [comment]
Cherry pick clang 6 patches from ctu-clang7 branch to ctu-clang7-expectedT branch that already contains the error handling of handling patch from Balazs (https://reviews.llvm.org/D51633)

Then at the end ctu-clang7-expectedT should be the new ctu-clang7.

**Comment by martong** [comment]
I am finished with the rebase and force pushed the ctu-clang7 branch.
Saved the former ctu-clang7 branch as `ctu-clang7-pre-expectedT`
