### ISSUE TITLE
Do not forget to enable unupported construct handling

### ISSUE THREAD

**Issue by martong** [Ericsson/clang#515]
During rebase of Balazs's error handling we cannot use the unsupported construct error until the error is not published via ASTImporter's public interface.
Regarding to this commit https://github.com/Ericsson/clang/commit/e821f56a02652f33725a24f1ed3cda99f90af7b6
We have to handle this once the public interface contains Expected<T> too.

**Comment by balazske** [comment]
https://github.com/Ericsson/clang/pull/527
adds the statistics
