### ISSUE TITLE
introduce a new clang parameter to report ODR errors as warnings

### ISSUE THREAD

**Issue by dkrupp** [Ericsson/clang#532]

**Comment by gamesh411** [comment]
Make odr diagnostics uniform, making them warnings, and assigning them to diaggroups, so they can be propagated to errors. Fix unit tests to consider odr errors warnings.

**Comment by gamesh411** [comment]
#551 makes the odr-related errors warnings by default

**Comment by dkrupp** [comment]
create an upstream patch for this.

**Comment by gamesh411** [comment]
phabricator review:
https://reviews.llvm.org/D55646

**Comment by dkrupp** [comment]
Let's find out why don't we see any warnings. Try to explicitly switch on ODR warnings. we would use this for internal debugging.
