### ISSUE TITLE
Handle visibility everywhere after lookup

### ISSUE THREAD

**Issue by martong** [Ericsson/clang#540]
We should implement a visibility check on all lookup results. Atm we check visibility only in case of `FunctionDecl` and `VarDecl`. We should however do that with all other `Decl` nodes (`TypedefNameDecl`, `RecordDecl`, etc). This is important because unnamed namespaces of different TUs may have nodes with the same name but with different definition.

**Comment by balazske** [comment]
related:
#631 #632 #633 #634 #635 #639 #640 #644

**Comment by balazske** [comment]
related: #632

**Comment by dkrupp** [comment]
continue with fixing rest of the nodes. for example templates
