### ISSUE TITLE
create buildbot for CTU analysis

### ISSUE THREAD

**Issue by dkrupp** [Ericsson/clang#558]
we have a VM already in azure. take it over from Lorinc

**Comment by dkrupp** [comment]
depends on #509

**Comment by dkrupp** [comment]
For TMUX we need teh followign patches
https://reviews.llvm.org/D53818
Balazs will commit this.

Endre to try master version on curl or any other project that may work.

**Comment by dkrupp** [comment]
-we tried to analyze curl with scan-build
-scan-build needs to be patched to remove -Werror-incompatible... from the build commands -> TODO: patch to be created
-When the above was done, there were assertions -> TODO: which patches are needed to get rid off these asserts?

-scan-build logging is outdated: There are problems with " and whitespaces -> We will patch this??

-git was investigated, but scan-build cannot log it.

try CODECHECKER for the buildbot (tmux/curl/... analyis) 
we dont' want to patch scan-build.

**Comment by dkrupp** [comment]
-ODR errors to warnings patch to be created in phabricator
-now curl has 3 remaining crashes investigate why.
-create patch for CodeChecker to recognize clang8 clangExtDefMapping binary name

**Comment by gamesh411** [comment]
OS patch in 2 parts:
https://reviews.llvm.org/D58897
https://reviews.llvm.org/D59761

**Comment by dkrupp** [comment]
-vm is started
-rewriting to codechecker anlayze is ongoing

**Comment by dkrupp** [comment]
-there is some issue with the git cloning. once it is resovled we can connect this to central buildbot network.

**Comment by gamesh411** [comment]
Current prototype is running at: 
http://13.90.81.45:8010/
the sources are located in a git repo:
https://github.com/gamesh411/llvm-ctu-ci-prototype
Also I have sent a mail to the maintainer of the buildbot network.

**Comment by gamesh411** [comment]
Phabricator patch for first part:
https://reviews.llvm.org/D61848
