### ISSUE TITLE
add clang to CTU analysis pipeline

### ISSUE THREAD

**Issue by dkrupp** [Ericsson/clang#571]
On ci2

**Comment by dkrupp** [comment]
jenkins timeouts due to too long job. fix that.

**Comment by gamesh411** [comment]
Long-running Jenkins jobs should have this parameter defined at high-enough value:
org.jenkinsci.plugins.durabletask.BourneShellScript.HEARTBEAT_CHECK_INTERVAL
I have set it on the relevant Jenkins server to 86400.
This can be set via the console, or by specifying it in JAVA_OPTS when using the docker image:
console:

Console:
System.setProperty("org.jenkinsci.plugins.durabletask.BourneShellScript.HEARTBEAT_CHECK_INTERVAL", "86400");

Option:
...
JAVA_OPTS="-Dorg.jenkinsci.plugins.durabletask.BourneShellScript.HEARTBEAT_CHECK_INTERVAL=86400"
...

**Comment by martong** [comment]
> Console:

Is this the script console?

**Comment by gamesh411** [comment]
Yes, the one which can be accessed via "Manage Jenkins" > "Script Console".
