### ISSUE TITLE
introduce parameter to control the number of TUs to import

### ISSUE THREAD

**Issue by dkrupp** [Ericsson/clang#605]
in order to constraint the memory usage of the CTU analysis.

**Comment by dkrupp** [comment]
https://github.com/Ericsson/clang/pull/619

**Comment by dkrupp** [comment]
create OS patch

**Comment by gamesh411** [comment]
patch: https://reviews.llvm.org/D59798

**Comment by dkrupp** [comment]
Please reimplement the option in ctu-clang7 branch so that the parameter is given like
-cc1 -analyzer-config ctu-import-threshold=22

**Comment by gamesh411** [comment]
PR for our branch: #642
