### ISSUE TITLE
revert ODR warning patch

### ISSUE THREAD

**Issue by dkrupp** [Ericsson/clang#611]
abandon https://reviews.llvm.org/D55646

Sema ODR probelms will be errors
ASTImporter ODR problems should be warnings

and create an new open source patch.

**Comment by gamesh411** [comment]
Abandoned old patch, new PR: #618.

**Comment by dkrupp** [comment]
phabricator patch needed

**Comment by gamesh411** [comment]
https://reviews.llvm.org/D58897
