### ISSUE TITLE
Review clang/master branch status on open source projects

### ISSUE THREAD

**Issue by dkrupp** [Ericsson/clang#621]
in practice:
make the /job/upstream%20master%20tests/
work. 

The goal is that TMUX is analyzed without crash and error using scan build.
Identify the open source patched needed for this.

**Comment by dkrupp** [comment]
*recreate logs with scan build.
*apply error->warning patch https://reviews.llvm.org/D58897

**Comment by dkrupp** [comment]
Endre will try to fix CodeChecker to work with clang-master.

**Comment by dkrupp** [comment]
-curl still has 3 crashes
tmux, vim, redis

**Comment by gamesh411** [comment]
tmux: 122 / 144 
vim: 84 / 41
redis: too many missing files errors
main cause of crashes:
clang::SourceManager::isBeforeInTranslationUnit

**Comment by dkrupp** [comment]
try to find the reason for the source location related problem

**Comment by gamesh411** [comment]
example in tmux 2.8:
conflicting locations:

/compat/tree.h:721:9
```
//...
721 #define RB_FIND(name, x, y) name##_RB_FIND(x, y)
//...
```

/arguments.c:56:10
```
//...
 49 /* Find a flag in the arguments tree. */
 50 static struct args_entry *
 51 args_find(struct args *args, u_char ch)
 52 {
 53   struct args_entry>entry; 
 54
 55   entry.flag = ch;
 56   return (RB_FIND(args_tree, &args->tree, &entry));
 57 }
//...
```

These locations are reported to be uncomparable.
RB_FIND macro definition seems to be the problem.
