### ISSUE TITLE
find ODR false positives in open source projects

### ISSUE THREAD

**Issue by dkrupp** [Ericsson/clang#622]

**Comment by balazske** [comment]
One false ODR condition was found in protobuf, related pull requests:
#613 
#616 
#624

**Comment by balazske** [comment]
Now looking at Bitcoin.

**Comment by balazske** [comment]
Bitcoin related: #626

**Comment by balazske** [comment]
After #631 there are no more ODR warnings in bitcoin.

**Comment by martong** [comment]
Nice work!

**Comment by dkrupp** [comment]
try to analyze the remaining ODR erros if they are coming from the Importing
redis, xerces
