### ISSUE TITLE
Assertion `!isCompleteDefinition() && "Cannot redefine record!"' failed.

### ISSUE THREAD

**Issue by martong** [Ericsson/clang#643]
This happens during ctu analysis of LLVM/Clang release_70.

**Comment by martong** [comment]
The problem is related to LambdaExprs and to their LambdaClass.

There are 3 different problems, which will be addressed in 3 PRs:
1) We import the definition of the CXXRecordDecl connectetd to the lambda in VisitLambdaExpr. That is a mistake, because when we directly import the lambda class it will never have a definition!
2) Sturctural Eq fails to distinguish lambdas if they are at different source locations
3) Structural EQ failes to distinguish lambdas with different operator() signatures. The solution to this is check the methods of the lambda classes for equivalency.

**Comment by martong** [comment]
#646, #647 PRs

**Comment by dkrupp** [comment]
and #648
