### ISSUE TITLE
BugReporterVisitors.cpp:440 assertion: `VR->getDecl()->isStaticLocal() && "non-static stackless VarRegion"'

### ISSUE THREAD

**Issue by gerazo** [Ericsson/clang#76]
in openssl, 46 files:

/mnt/storage/gerazo/clang_asan/clang/tools/scan-build-py/bin/analyze-cc -I/mnt/storage/gerazo/clang_asan/openssl -I/mnt/storage/gerazo/clang_asan/openssl/include -I/u
sr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include -DDSO_DLFCN -
DHAVE_DLFCN_H -DNDEBUG -DOPENSSL_THREADS -DOPENSSL_NO_STATIC_ENGINE -DOPENSSL_PIC -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF
2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DPADLOCK_ASM -DPOLY1305_ASM -DOPENSSLDIR
="/usr/local/ssl" -DENGINESDIR="/usr/local/lib/engines-1.1" -Wall -O3 -pthread -m64 -DL_ENDIAN -Wa,--noexecstack -MMD -MF apps/x509.d.tmp -MT apps/x509.o -c -o /mnt/s
torage/gerazo/clang_asan/openssl/apps/x509.o /mnt/storage/gerazo/clang_asan/openssl/apps/x509.c
analyze: INFO: execute compiler: gcc -I/mnt/storage/gerazo/clang_asan/openssl -I/mnt/storage/gerazo/clang_asan/openssl/include -I/usr/include/c++/5 -I/usr/include/x86
_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include -DDSO_DLFCN -DHAVE_DLFCN_H -DNDEBUG -DOPENSSL_TH
READS -DOPENSSL_NO_STATIC_ENGINE -DOPENSSL_PIC -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512
_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DPADLOCK_ASM -DPOLY1305_ASM -DOPENSSLDIR=/usr/local/ssl -DENGINESDIR=/usr/l
ocal/lib/engines-1.1 -Wall -O3 -pthread -m64 -DL_ENDIAN -Wa,--noexecstack -MMD -MF apps/x509.d.tmp -MT apps/x509.o -c -o /mnt/storage/gerazo/clang_asan/openssl/apps/x
509.o /mnt/storage/gerazo/clang_asan/openssl/apps/x509.c
analyze: INFO: Importing function _Z24X509_STORE_CTX_get_errorP17x509_store_ctx_st@x86_64 from /mnt/storage/gerazo/clang_asan/openssl/.xtu//ast/x86_64/mnt/storage/ger
azo/clang_asan/openssl/crypto/x509/x509_vfy.c.ast
analyze: INFO: Importing function _Z31X509_STORE_CTX_get_current_certP17x509_store_ctx_st@x86_64 from /mnt/storage/gerazo/clang_asan/openssl/.xtu//ast/x86_64/mnt/stor
age/gerazo/clang_asan/openssl/crypto/x509/x509_vfy.c.ast
analyze: INFO: Importing function _Z21X509_get_subject_namePK7x509_st@x86_64 from /mnt/storage/gerazo/clang_asan/openssl/.xtu//ast/x86_64/mnt/storage/gerazo/clang_asa
n/openssl/crypto/x509/x509_cmp.c.ast
analyze: INFO: Importing function _Z10print_nameP6bio_stPKcP12X509_name_stm@x86_64 from /mnt/storage/gerazo/clang_asan/openssl/.xtu//ast/x86_64/mnt/storage/gerazo/cla
ng_asan/openssl/apps/apps.c.ast
analyze: INFO: Importing function _Z17X509_NAME_onelinePK12X509_name_stPci@x86_64 from /mnt/storage/gerazo/clang_asan/openssl/.xtu//ast/x86_64/mnt/storage/gerazo/clan
g_asan/openssl/crypto/x509/x509_obj.c.ast
analyze: INFO: Importing function _Z8BIO_putsP6bio_stPKc@x86_64 from /mnt/storage/gerazo/clang_asan/openssl/.xtu//ast/x86_64/mnt/storage/gerazo/clang_asan/openssl/cry
pto/bio/bio_lib.c.ast
analyze: INFO: Importing function _Z11CRYPTO_freePvPKci@x86_64 from /mnt/storage/gerazo/clang_asan/openssl/.xtu//ast/x86_64/mnt/storage/gerazo/clang_asan/openssl/cryp
to/mem.c.ast
analyze: INFO: Importing function _Z30X509_STORE_CTX_get_error_depthP17x509_store_ctx_st@x86_64 from /mnt/storage/gerazo/clang_asan/openssl/.xtu//ast/x86_64/mnt/stora
ge/gerazo/clang_asan/openssl/crypto/x509/x509_vfy.c.ast
analyze: INFO: Importing function _Z29X509_verify_cert_error_stringl@x86_64 from /mnt/storage/gerazo/clang_asan/openssl/.xtu//ast/x86_64/mnt/storage/gerazo/clang_asan
/openssl/crypto/x509/x509_txt.c.ast
analyze: INFO: Importing function _Z10BIO_printfP6bio_stPKcz@x86_64 from /mnt/storage/gerazo/clang_asan/openssl/.xtu//ast/x86_64/mnt/storage/gerazo/clang_asan/openssl
/crypto/bio/b_print.c.ast
analyze: INFO: Importing function _Z13ERR_put_erroriiiPKci@x86_64 from /mnt/storage/gerazo/clang_asan/openssl/.xtu//ast/x86_64/mnt/storage/gerazo/clang_asan/openssl/c
rypto/err/err.c.ast
analyze: INFO: Importing function _Z13ERR_get_statev@x86_64 from /mnt/storage/gerazo/clang_asan/openssl/.xtu//ast/x86_64/mnt/storage/gerazo/clang_asan/openssl/crypto/
err/err.c.ast
analyze: INFO: Importing function _Z22CRYPTO_THREAD_run_oncePiPFvvE@x86_64 from /mnt/storage/gerazo/clang_asan/openssl/.xtu//ast/x86_64/mnt/storage/gerazo/clang_asan/
openssl/crypto/threads_pthread.c.ast
analyze: INFO: Importing function _Z23CRYPTO_THREAD_get_localPj@x86_64 from /mnt/storage/gerazo/clang_asan/openssl/.xtu//ast/x86_64/mnt/storage/gerazo/clang_asan/open
ssl/crypto/threads_pthread.c.ast
analyze: INFO: Importing function _Z13CRYPTO_zallocmPKci@x86_64 from /mnt/storage/gerazo/clang_asan/openssl/.xtu//ast/x86_64/mnt/storage/gerazo/clang_asan/openssl/cry
pto/mem.c.ast
analyze: INFO: Importing function _Z23CRYPTO_THREAD_set_localPjPv@x86_64 from /mnt/storage/gerazo/clang_asan/openssl/.xtu//ast/x86_64/mnt/storage/gerazo/clang_asan/op
enssl/crypto/threads_pthread.c.ast
analyze: INFO: Importing function _Z19OPENSSL_init_cryptomPK21ossl_init_settings_st@x86_64 from /mnt/storage/gerazo/clang_asan/openssl/.xtu//ast/x86_64/mnt/storage/ge
razo/clang_asan/openssl/crypto/init.c.ast
analyze: INFO: Importing function _Z22ossl_init_thread_startm@x86_64 from /mnt/storage/gerazo/clang_asan/openssl/.xtu//ast/x86_64/mnt/storage/gerazo/clang_asan/openssl/crypto/init.c.ast
analyze: INFO: _ZL5callbiP17x509_store_ctx_st@x86_64 empty_wl not_exhausted no_block_aborted
analyze: INFO: Importing function _Z14X509_STORE_newv@x86_64 from /mnt/storage/gerazo/clang_asan/openssl/.xtu//ast/x86_64/mnt/storage/gerazo/clang_asan/openssl/crypto/x509/x509_lu.c.ast
analyze: INFO: Importing function _Z10NCONF_freeP7conf_st@x86_64 from /mnt/storage/gerazo/clang_asan/openssl/.xtu//ast/x86_64/mnt/storage/gerazo/clang_asan/openssl/crypto/conf/conf_lib.c.ast
analyze: INFO: Importing function _Z12BIO_free_allP6bio_st@x86_64 from /mnt/storage/gerazo/clang_asan/openssl/.xtu//ast/x86_64/mnt/storage/gerazo/clang_asan/openssl/crypto/bio/bio_lib.c.ast
analyze: INFO: Importing function _Z15X509_STORE_freeP13x509_store_st@x86_64 from /mnt/storage/gerazo/clang_asan/openssl/.xtu//ast/x86_64/mnt/storage/gerazo/clang_asan/openssl/crypto/x509/x509_lu.c.ast
analyze: INFO: Importing function _Z13X509_REQ_freeP11X509_req_st@x86_64 from /mnt/storage/gerazo/clang_asan/openssl/.xtu//ast/x86_64/mnt/storage/gerazo/clang_asan/openssl/crypto/x509/x_req.c.ast
analyze: INFO: Importing function _Z14ASN1_item_freeP13ASN1_VALUE_stPK12ASN1_ITEM_st@x86_64 from /mnt/storage/gerazo/clang_asan/openssl/.xtu//ast/x86_64/mnt/storage/gerazo/clang_asan/openssl/crypto/asn1/tasn_fre.c.ast
analyze: INFO: Importing function _Z22asn1_string_embed_freeP14asn1_string_sti@x86_64 from /mnt/storage/gerazo/clang_asan/openssl/.xtu//ast/x86_64/mnt/storage/gerazo/clang_asan/openssl/crypto/asn1/asn1_lib.c.ast
analyze: INFO: Importing function _Z9X509_freeP7x509_st@x86_64 from /mnt/storage/gerazo/clang_asan/openssl/.xtu//ast/x86_64/mnt/storage/gerazo/clang_asan/openssl/crypto/x509/x_x509.c.ast
analyze: INFO: Importing function _Z16ASN1_OBJECT_freeP14asn1_object_st@x86_64 from /mnt/storage/gerazo/clang_asan/openssl/.xtu//ast/x86_64/mnt/storage/gerazo/clang_asan/openssl/crypto/asn1/a_object.c.ast
analyze: INFO: Importing function _Z13EVP_PKEY_freeP11evp_pkey_st@x86_64 from /mnt/storage/gerazo/clang_asan/openssl/.xtu//ast/x86_64/mnt/storage/gerazo/clang_asan/openssl/crypto/evp/p_lib.c.ast
analyze: INFO: Importing function _Z15OPENSSL_sk_freeP8stack_st@x86_64 from /mnt/storage/gerazo/clang_asan/openssl/.xtu//ast/x86_64/mnt/storage/gerazo/clang_asan/openssl/crypto/stack/stack.c.ast
analyze: INFO: Importing function _Z17ASN1_INTEGER_freeP14asn1_string_st@x86_64 from /mnt/storage/gerazo/clang_asan/openssl/.xtu//ast/x86_64/mnt/storage/gerazo/clang_asan/openssl/crypto/asn1/tasn_typ.c.ast
analyze: INFO: Importing function _Z16ASN1_STRING_freeP14asn1_string_st@x86_64 from /mnt/storage/gerazo/clang_asan/openssl/.xtu//ast/x86_64/mnt/storage/gerazo/clang_asan/openssl/crypto/asn1/asn1_lib.c.ast
analyze: INFO: Importing function _Z19OPENSSL_sk_pop_freeP8stack_stPFvPvE@x86_64 from /mnt/storage/gerazo/clang_asan/openssl/.xtu//ast/x86_64/mnt/storage/gerazo/clang_asan/openssl/crypto/stack/stack.c.ast
analyze: INFO: Importing function _Z14release_engineP9engine_st@x86_64 from /mnt/storage/gerazo/clang_asan/openssl/.xtu//ast/x86_64/mnt/storage/gerazo/clang_asan/openssl/apps/apps.c.ast
analyze: INFO: Importing function _Z12asn1_do_lockPP13ASN1_VALUE_stiPK12ASN1_ITEM_st@x86_64 from /mnt/storage/gerazo/clang_asan/openssl/.xtu//ast/x86_64/mnt/storage/gerazo/clang_asan/openssl/crypto/asn1/tasn_utl.c.ast
analyze: INFO: Importing function _Z13asn1_enc_freePP13ASN1_VALUE_stPK12ASN1_ITEM_st@x86_64 from /mnt/storage/gerazo/clang_asan/openssl/.xtu//ast/x86_64/mnt/storage/gerazo/clang_asan/openssl/crypto/asn1/tasn_utl.c.ast
analyze: INFO: Importing function _Z11asn1_do_adbPP13ASN1_VALUE_stPK16ASN1_TEMPLATE_sti@x86_64 from /mnt/storage/gerazo/clang_asan/openssl/.xtu//ast/x86_64/mnt/storage/gerazo/clang_asan/openssl/crypto/asn1/tasn_utl.c.ast
analyze: INFO: Importing function _Z16ASN1_INTEGER_getPK14asn1_string_st@x86_64 from /mnt/storage/gerazo/clang_asan/openssl/.xtu//ast/x86_64/mnt/storage/gerazo/clang_asan/openssl/crypto/asn1/a_int.c.ast
analyze: INFO: Importing function _Z18asn1_get_field_ptrPP13ASN1_VALUE_stPK16ASN1_TEMPLATE_st@x86_64 from /mnt/storage/gerazo/clang_asan/openssl/.xtu//ast/x86_64/mnt/storage/gerazo/clang_asan/openssl/crypto/asn1/tasn_utl.c.ast
analyze: INFO: Importing function _Z11OBJ_obj2nidPK14asn1_object_st@x86_64 from /mnt/storage/gerazo/clang_asan/openssl/.xtu//ast/x86_64/mnt/storage/gerazo/clang_asan/openssl/crypto/objects/obj_dat.c.ast
analyze: INFO: _Z9x509_mainiPPc@x86_64 has_work_wl not_exhausted no_block_aborted
analyze: INFO: clang-5.0: /mnt/storage/gerazo/clang_asan/llvm/tools/clang/lib/StaticAnalyzer/Core/BugReporterVisitors.cpp:440: bool isInitializationOfVar(const clang::ento::ExplodedNode*, const clang::ento::VarRegion*): Assertion `VR->getDecl()->isStaticLocal() && "non-static stackless VarRegion"' failed.
analyze: INFO: #0 0x00007f011dba7077 (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x4a077)
analyze: INFO: #1 0x000000000242e613 llvm::sys::PrintStackTrace(llvm::raw_ostream&) /mnt/storage/gerazo/clang_asan/llvm/lib/Support/Unix/Signals.inc:406:0
analyze: INFO: #2 0x000000000242a309 llvm::sys::RunSignalHandlers() /mnt/storage/gerazo/clang_asan/llvm/lib/Support/Signals.cpp:44:0
analyze: INFO: #3 0x000000000242a6e7 SignalHandler(int) /mnt/storage/gerazo/clang_asan/llvm/lib/Support/Unix/Signals.inc:246:0
analyze: INFO: #4 0x00007f011d951390 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x11390)
analyze: INFO: #5 0x00007f011c6c4428 gsignal /build/glibc-t3gR2i/glibc-2.23/signal/../sysdeps/unix/sysv/linux/raise.c:54:0
analyze: INFO: #6 0x00007f011c6c602a abort /build/glibc-t3gR2i/glibc-2.23/stdlib/abort.c:91:0
analyze: INFO: #7 0x00007f011c6bcbd7 __assert_fail_base /build/glibc-t3gR2i/glibc-2.23/assert/assert.c:92:0
analyze: INFO: #8 0x00007f011c6bcc82 (/lib/x86_64-linux-gnu/libc.so.6+0x2dc82)
analyze: INFO: #9 0x00000000043c79a2 /mnt/storage/gerazo/clang_asan/llvm/tools/clang/include/clang/AST/Expr.h:2956:0
analyze: INFO: #10 0x00000000043c79a2 /mnt/storage/gerazo/clang_asan/llvm/tools/clang/include/clang/AST/Expr.h:3041:0
analyze: INFO: #11 0x00000000043c79a2 clang::ento::FindLastStoreBRVisitor::VisitNode(clang::ento::ExplodedNode const*, clang::ento::ExplodedNode const*, clang::ento::BugReporterContext&, clang::ento::BugReport&) /mnt/storage/gerazo/clang_asan/llvm/tools/clang/lib/StaticAnalyzer/Core/BugReporterVisitors.cpp:500:0
analyze: INFO: #12 0x00000000043ad401 /usr/include/c++/5/bits/shared_ptr_base.h:658:0
analyze: INFO: #13 0x00000000043ad401 /usr/include/c++/5/bits/shared_ptr_base.h:925:0
analyze: INFO: #14 0x00000000043ad401 /usr/include/c++/5/bits/shared_ptr.h:93:0
analyze: INFO: #15 0x00000000043ad401 GenerateVisitorsOnlyPathDiagnostic /mnt/storage/gerazo/clang_asan/llvm/tools/clang/lib/StaticAnalyzer/Core/BugReporter.cpp:522:0
analyze: INFO: #16 0x00000000043ad401 clang::ento::GRBugReporter::generatePathDiagnostic(clang::ento::PathDiagnostic&, clang::ento::PathDiagnosticConsumer&, llvm::ArrayRef<clang::ento::BugReport*>&) /mnt/storage/gerazo/clang_asan/llvm/tools/clang/lib/StaticAnalyzer/Core/BugReporter.cpp:3175:0
analyze: INFO: #17 0x000000000438ede1 clang::ento::BugReporter::FlushReport(clang::ento::BugReport*, clang::ento::PathDiagnosticConsumer&, llvm::ArrayRef<clang::ento::BugReport*>) /mnt/storage/gerazo/clang_asan/llvm/tools/clang/lib/StaticAnalyzer/Core/BugReporter.cpp:3454:0
analyze: INFO: #18 0x00000000043a787e clang::ento::BugReporter::FlushReport(clang::ento::BugReportEquivClass&) /mnt/storage/gerazo/clang_asan/llvm/tools/clang/lib/StaticAnalyzer/Core/BugReporter.cpp:3422:0
analyze: INFO: #19 0x00000000043b3b54 clang::ento::BugReporter::FlushReports() /mnt/storage/gerazo/clang_asan/llvm/tools/clang/lib/StaticAnalyzer/Core/BugReporter.cpp:2783:0
analyze: INFO: #20 0x0000000003e43cad /usr/include/c++/5/bits/unique_ptr.h:235:0
analyze: INFO: #21 0x0000000003e43cad (anonymous namespace)::AnalysisConsumer::ActionExprEngine(clang::Decl*, bool, clang::ento::ExprEngine::InliningModes, llvm::DenseSet<clang::Decl const*, llvm::DenseMapInfo<clang::Decl const*> >*) [clone .part.4350] [clone .constprop.4499] /mnt/storage/gerazo/clang_asan/llvm/tools/clang/lib/StaticAnalyzer/Frontend/AnalysisConsumer.cpp:817:0
analyze: INFO: #22 0x0000000003e44f92 /mnt/storage/gerazo/clang_asan/llvm/tools/clang/lib/StaticAnalyzer/Frontend/AnalysisConsumer.cpp:861:0
analyze: INFO: #23 0x0000000003e44f92 (anonymous namespace)::AnalysisConsumer::HandleCode(clang::Decl*, unsigned int, clang::ento::ExprEngine::InliningModes, llvm::DenseSet<clang::Decl const*, llvm::DenseMapInfo<clang::Decl const*> >*) [clone .constprop.4495] /mnt/storage/gerazo/clang_asan/llvm/tools/clang/lib/StaticAnalyzer/Frontend/AnalysisConsumer.cpp:791:0
analyze: INFO: #24 0x0000000003e5fa71 /mnt/storage/gerazo/clang_asan/llvm/include/llvm/ADT/DenseMap.h:67:0
analyze: INFO: #25 0x0000000003e5fa71 /mnt/storage/gerazo/clang_asan/llvm/include/llvm/ADT/DenseSet.h:151:0
analyze: INFO: #26 0x0000000003e5fa71 (anonymous namespace)::AnalysisConsumer::HandleDeclsCallGraph(unsigned int) [clone .constprop.4443] /mnt/storage/gerazo/clang_asan/llvm/tools/clang/lib/StaticAnalyzer/Frontend/AnalysisConsumer.cpp:575:0
analyze: INFO: #27 0x0000000003e62a3c /usr/include/c++/5/bits/unique_ptr.h:305:0
analyze: INFO: #28 0x0000000003e62a3c /usr/include/c++/5/bits/unique_ptr.h:291:0
analyze: INFO: #29 0x0000000003e62a3c (anonymous namespace)::AnalysisConsumer::HandleTranslationUnit(clang::ASTContext&) [clone .part.4400] [clone .constprop.4442] /mnt/storage/gerazo/clang_asan/llvm/tools/clang/lib/StaticAnalyzer/Frontend/AnalysisConsumer.cpp:657:0
analyze: INFO: #30 0x00000000045bebd3 clang::ParseAST(clang::Sema&, bool, bool) /mnt/storage/gerazo/clang_asan/llvm/tools/clang/lib/Parse/ParseAST.cpp:159:0
analyze: INFO: #31 0x0000000002ed9446 clang::FrontendAction::Execute() /mnt/storage/gerazo/clang_asan/llvm/tools/clang/lib/Frontend/FrontendAction.cpp:459:0
analyze: INFO: #32 0x0000000002e6e84c clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) /mnt/storage/gerazo/clang_asan/llvm/tools/clang/lib/Frontend/CompilerInstance.cpp:954:0
analyze: INFO: #33 0x0000000003018d39 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) /mnt/storage/gerazo/clang_asan/llvm/tools/clang/lib/FrontendTool/ExecuteCompilerInvocation.cpp:249:0
analyze: INFO: #34 0x0000000000b41878 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) /mnt/storage/gerazo/clang_asan/llvm/tools/clang/tools/driver/cc1_main.cpp:221:0
analyze: INFO: #35 0x0000000000a7dc43 ExecuteCC1Tool /mnt/storage/gerazo/clang_asan/llvm/tools/clang/tools/driver/driver.cpp:299:0
analyze: INFO: #36 0x0000000000a7dc43 main /mnt/storage/gerazo/clang_asan/llvm/tools/clang/tools/driver/driver.cpp:380:0
analyze: INFO: #37 0x00007f011c6af830 __libc_start_main /build/glibc-t3gR2i/glibc-2.23/csu/../csu/libc-start.c:325:0
analyze: INFO: #38 0x0000000000b39f79 _start (/mnt/storage/gerazo/clang_asan/build_debasan/bin/clang-5.0+0xb39f79)
analyze: INFO: Stack dump:
analyze: INFO: 0.       Program arguments: /mnt/storage/gerazo/clang_asan/build_debasan/bin/clang-5.0 -cc1 -triple x86_64-unknown-linux-gnu -analyze -disable-free -main-file-name x509.c -analyzer-store=region -analyzer-opt-analyze-nested-blocks -analyzer-eagerly-assume -analyzer-checker=core -analyzer-checker=apiModeling -analyzer-checker=unix -analyzer-checker=deadcode -analyzer-checker=security.insecureAPI.UncheckedReturn -analyzer-checker=security.insecureAPI.getpw -analyzer-checker=security.insecureAPI.gets -analyzer-checker=security.insecureAPI.mktemp -analyzer-checker=security.insecureAPI.mkstemp -analyzer-checker=security.insecureAPI.vfork -analyzer-checker=nullability.NullPassedToNonnull -analyzer-checker=nullability.NullReturnedFromNonnull -analyzer-output plist-multi-file -w -analyzer-config xtu-dir=/mnt/storage/gerazo/clang_asan/openssl/.xtu -analyzer-config reanalyze-xtu-visited=true -analyzer-stats -mrelocation-model static -mthread-model posix -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -fuse-init-array -target-cpu x86-64 -momit-leaf-frame-pointer -dwarf-column-info -debugger-tuning=gdb -resource-dir /mnt/storage/gerazo/clang_asan/build_debasan/bin/../lib/clang/5.0.0 -I /mnt/storage/gerazo/clang_asan/openssl -I /mnt/storage/gerazo/clang_asan/openssl/include -I /usr/include/c++/5 -I /usr/include/x86_64-linux-gnu/c++/5 -I /usr/include/c++/5/backward -I /usr/local/include -I /usr/include/x86_64-linux-gnu -I /usr/include -D DSO_DLFCN -D HAVE_DLFCN_H -D NDEBUG -D OPENSSL_THREADS -D OPENSSL_NO_STATIC_ENGINE -D OPENSSL_PIC -D OPENSSL_IA32_SSE2 -D OPENSSL_BN_ASM_MONT -D OPENSSL_BN_ASM_MONT5 -D OPENSSL_BN_ASM_GF2m -D SHA1_ASM -D SHA256_ASM -D SHA512_ASM -D RC4_ASM -D MD5_ASM -D AES_ASM -D VPAES_ASM -D BSAES_ASM -D GHASH_ASM -D ECP_NISTZ256_ASM -D PADLOCK_ASM -D POLY1305_ASM -D OPENSSLDIR=/usr/local/ssl -D ENGINESDIR=/usr/local/lib/engines-1.1 -D L_ENDIAN -internal-isystem /usr/local/include -internal-isystem /mnt/storage/gerazo/clang_asan/build_debasan/bin/../lib/clang/5.0.0/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -O3 -fdebug-compilation-dir /mnt/storage/gerazo/clang_asan/openssl -ferror-limit 19 -fmessage-length 0 -pthread -fobjc-runtime=gcc -fdiagnostics-show-option -vectorize-loops -vectorize-slp -o /mnt/storage/gerazo/clang_asan/openssl/.xtu-out/report-uwKS6w.plist -x c /mnt/storage/gerazo/clang_asan/openssl/apps/x509.c
analyze: INFO: 1.       <eof> parser at end of file

**Comment by gerazo** [comment]
It seems that this bug is not harmful. Analysis runs down without show stopper error after assertion.

**Comment by Xazax-hun** [comment]
It would be good to know however why did not assign the analyzer any stack region for the vardecl.

**Comment by martong** [comment]
@gerazo 
Is this bug still relevant in latest ctu-clang6?

**Comment by gerazo** [comment]
Just did a full rerun. This bug is gone.
