### ISSUE TITLE
external variable in multiple translation units

### ISSUE THREAD

**Issue by gerazo** [Ericsson/clang#79]
in openssl:

/mnt/storage/gerazo/clang_asan/clang/tools/scan-build-py/bin/analyze-cc -I/mnt/storage/gerazo/clang_asan/openssl -I/mnt/storage/gerazo/clang_asan/openssl/include -I/u
sr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include -DDSO_DLFCN -
DHAVE_DLFCN_H -DNDEBUG -DOPENSSL_THREADS -DOPENSSL_NO_STATIC_ENGINE -DOPENSSL_PIC -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF
2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DPADLOCK_ASM -DPOLY1305_ASM -DOPENSSLDIR
="/usr/local/ssl" -DENGINESDIR="/usr/local/lib/engines-1.1" -Wall -O3 -pthread -m64 -DL_ENDIAN -Wa,--noexecstack -MMD -MF apps/pkcs7.d.tmp -MT apps/pkcs7.o -c -o /mnt
/storage/gerazo/clang_asan/openssl/apps/pkcs7.o /mnt/storage/gerazo/clang_asan/openssl/apps/pkcs7.c
analyze: INFO: execute compiler: gcc -I/mnt/storage/gerazo/clang_asan/openssl -I/mnt/storage/gerazo/clang_asan/openssl/include -I/usr/include/c++/5 -I/usr/include/x86
_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include -DDSO_DLFCN -DHAVE_DLFCN_H -DNDEBUG -DOPENSSL_TH
READS -DOPENSSL_NO_STATIC_ENGINE -DOPENSSL_PIC -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512
_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DPADLOCK_ASM -DPOLY1305_ASM -DOPENSSLDIR=/usr/local/ssl -DENGINESDIR=/usr/l
ocal/lib/engines-1.1 -Wall -O3 -pthread -m64 -DL_ENDIAN -Wa,--noexecstack -MMD -MF apps/pkcs7.d.tmp -MT apps/pkcs7.o -c -o /mnt/storage/gerazo/clang_asan/openssl/apps
/pkcs7.o /mnt/storage/gerazo/clang_asan/openssl/apps/pkcs7.c
analyze: INFO: Importing function _Z8opt_initiPPcPK10options_st@x86_64 from /mnt/storage/gerazo/clang_asan/openssl/.xtu//ast/x86_64/mnt/storage/gerazo/clang_asan/open
ssl/apps/opt.c.ast
analyze: INFO: Importing function _Z8opt_nextv@x86_64 from /mnt/storage/gerazo/clang_asan/openssl/.xtu//ast/x86_64/mnt/storage/gerazo/clang_asan/openssl/apps/opt.c.as
t
analyze: INFO: Importing function _Z12opt_num_restv@x86_64 from /mnt/storage/gerazo/clang_asan/openssl/.xtu//ast/x86_64/mnt/storage/gerazo/clang_asan/openssl/apps/opt
.c.ast
analyze: INFO: Importing function _Z16bio_open_defaultPKcci@x86_64 from /mnt/storage/gerazo/clang_asan/openssl/.xtu//ast/x86_64/mnt/storage/gerazo/clang_asan/openssl/
apps/apps.c.ast
analyze: INFO: Importing function _Z18PEM_read_bio_PKCS7P6bio_stPP8pkcs7_stPFiPciiPvES5_@x86_64 from /mnt/storage/gerazo/clang_asan/openssl/.xtu//ast/x86_64/mnt/stora
ge/gerazo/clang_asan/openssl/crypto/pem/pem_all.c.ast
analyze: INFO: Importing function _Z17PEM_ASN1_read_bioPFPvPS_PPKhlEPKcP6bio_stS0_PFiPciiS_ES_@x86_64 from /mnt/storage/gerazo/clang_asan/openssl/.xtu//ast/x86_64/mnt
/storage/gerazo/clang_asan/openssl/crypto/pem/pem_oth.c.ast
analyze: INFO: Importing function _Z18PEM_bytes_read_bioPPhPlPPcPKcP6bio_stPFiS2_iiPvES8_@x86_64 from /mnt/storage/gerazo/clang_asan/openssl/.xtu//ast/x86_64/mnt/stor
age/gerazo/clang_asan/openssl/crypto/pem/pem_lib.c.ast
analyze: INFO: Importing function _Z12PEM_read_bioP6bio_stPPcS2_PPhPl@x86_64 from /mnt/storage/gerazo/clang_asan/openssl/.xtu//ast/x86_64/mnt/storage/gerazo/clang_asa
n/openssl/crypto/pem/pem_lib.c.ast
analyze: INFO: Importing function _Z11CRYPTO_freePvPKci@x86_64 from /mnt/storage/gerazo/clang_asan/openssl/.xtu//ast/x86_64/mnt/storage/gerazo/clang_asan/openssl/cryp
to/mem.c.ast
analyze: INFO: Importing function _Z9d2i_PKCS7PP8pkcs7_stPPKhl@x86_64 from /mnt/storage/gerazo/clang_asan/openssl/.xtu//ast/x86_64/mnt/storage/gerazo/clang_asan/opens
sl/crypto/pkcs7/pk7_asn1.c.ast
analyze: INFO: In file included from /mnt/storage/gerazo/clang_asan/openssl/apps/pkcs7.c:14:
analyze: INFO: In file included from /mnt/storage/gerazo/clang_asan/openssl/apps/apps.h:22:
analyze: INFO: In file included from /mnt/storage/gerazo/clang_asan/openssl/include/openssl/x509.h:310:
analyze: INFO: /mnt/storage/gerazo/clang_asan/openssl/include/openssl/pkcs7.h:203:1: error: external variable 'PKCS7_ISSUER_AND_SERIAL_it' defined in multiple transla
tion units
analyze: INFO: DECLARE_ASN1_FUNCTIONS(PKCS7_ISSUER_AND_SERIAL)
analyze: INFO: ^
analyze: INFO: /mnt/storage/gerazo/clang_asan/openssl/include/openssl/asn1.h:216:39: note: expanded from macro 'DECLARE_ASN1_FUNCTIONS'
analyze: INFO: # define DECLARE_ASN1_FUNCTIONS(type) DECLARE_ASN1_FUNCTIONS_name(type, type)
analyze: INFO:                                       ^
analyze: INFO: /mnt/storage/gerazo/clang_asan/openssl/include/openssl/asn1.h:223:9: note: expanded from macro 'DECLARE_ASN1_FUNCTIONS_name'
analyze: INFO:         DECLARE_ASN1_ENCODE_FUNCTIONS(type, name, name)
analyze: INFO:         ^
analyze: INFO: /mnt/storage/gerazo/clang_asan/openssl/include/openssl/asn1.h:232:9: note: expanded from macro 'DECLARE_ASN1_ENCODE_FUNCTIONS'
analyze: INFO:         DECLARE_ASN1_ITEM(itname)
analyze: INFO:         ^
analyze: INFO: /mnt/storage/gerazo/clang_asan/openssl/include/openssl/asn1.h:328:40: note: expanded from macro 'DECLARE_ASN1_ITEM'
analyze: INFO:         OPENSSL_EXTERN const ASN1_ITEM name##_it;
analyze: INFO:                                        ^
analyze: INFO: <scratch space>:132:1: note: expanded from here
analyze: INFO: PKCS7_ISSUER_AND_SERIAL_it
analyze: INFO: ^
analyze: INFO: /mnt/storage/gerazo/clang_asan/openssl/crypto/pkcs7/pk7_asn1.c:112:3: note: also defined here
analyze: INFO: } ASN1_SEQUENCE_END(PKCS7_ISSUER_AND_SERIAL)
analyze: INFO:   ^
analyze: INFO: /mnt/storage/gerazo/clang_asan/openssl/include/openssl/asn1t.h:120:36: note: expanded from macro 'ASN1_SEQUENCE_END'
analyze: INFO: # define ASN1_SEQUENCE_END(stname) ASN1_SEQUENCE_END_name(stname, stname)
analyze: INFO:                                    ^
analyze: INFO: /mnt/storage/gerazo/clang_asan/openssl/include/openssl/asn1t.h:126:9: note: expanded from macro 'ASN1_SEQUENCE_END_name'
analyze: INFO:         ASN1_ITEM_start(tname) \
analyze: INFO:         ^
analyze: INFO: /mnt/storage/gerazo/clang_asan/openssl/include/openssl/asn1t.h:36:40: note: expanded from macro 'ASN1_ITEM_start'
analyze: INFO:         OPENSSL_GLOBAL const ASN1_ITEM itname##_it = {
analyze: INFO:                                        ^
analyze: INFO: <scratch space>:99:1: note: expanded from here
analyze: INFO: PKCS7_ISSUER_AND_SERIAL_it
analyze: INFO: ^
analyze: INFO: In file included from /mnt/storage/gerazo/clang_asan/openssl/apps/pkcs7.c:14:
analyze: INFO: In file included from /mnt/storage/gerazo/clang_asan/openssl/apps/apps.h:22:
analyze: INFO: In file included from /mnt/storage/gerazo/clang_asan/openssl/include/openssl/x509.h:310:
analyze: INFO: /mnt/storage/gerazo/clang_asan/openssl/include/openssl/pkcs7.h:219:1: error: external variable 'PKCS7_RECIP_INFO_it' defined in multiple translation units
analyze: INFO: DECLARE_ASN1_FUNCTIONS(PKCS7_RECIP_INFO)
analyze: INFO: ^
analyze: INFO: /mnt/storage/gerazo/clang_asan/openssl/include/openssl/asn1.h:216:39: note: expanded from macro 'DECLARE_ASN1_FUNCTIONS'
analyze: INFO: # define DECLARE_ASN1_FUNCTIONS(type) DECLARE_ASN1_FUNCTIONS_name(type, type)
analyze: INFO:                                       ^
analyze: INFO: /mnt/storage/gerazo/clang_asan/openssl/include/openssl/asn1.h:223:9: note: expanded from macro 'DECLARE_ASN1_FUNCTIONS_name'
analyze: INFO:         DECLARE_ASN1_ENCODE_FUNCTIONS(type, name, name)
analyze: INFO:         ^
analyze: INFO: /mnt/storage/gerazo/clang_asan/openssl/include/openssl/asn1.h:232:9: note: expanded from macro 'DECLARE_ASN1_ENCODE_FUNCTIONS'
analyze: INFO:         DECLARE_ASN1_ITEM(itname)
analyze: INFO:         ^
analyze: INFO: /mnt/storage/gerazo/clang_asan/openssl/include/openssl/asn1.h:328:40: note: expanded from macro 'DECLARE_ASN1_ITEM'
analyze: INFO:         OPENSSL_EXTERN const ASN1_ITEM name##_it;
analyze: INFO:                                        ^
analyze: INFO: <scratch space>:142:1: note: expanded from here
analyze: INFO: PKCS7_RECIP_INFO_it
analyze: INFO: ^
analyze: INFO: /mnt/storage/gerazo/clang_asan/openssl/crypto/pkcs7/pk7_asn1.c:140:3: note: also defined here
analyze: INFO: } ASN1_SEQUENCE_END_cb(PKCS7_RECIP_INFO, PKCS7_RECIP_INFO)
analyze: INFO:   ^
analyze: INFO: /mnt/storage/gerazo/clang_asan/openssl/include/openssl/asn1t.h:199:46: note: expanded from macro 'ASN1_SEQUENCE_END_cb'
analyze: INFO: # define ASN1_SEQUENCE_END_cb(stname, tname) ASN1_SEQUENCE_END_ref(stname, tname)
analyze: INFO:                                              ^
analyze: INFO: /mnt/storage/gerazo/clang_asan/openssl/include/openssl/asn1t.h:204:9: note: expanded from macro 'ASN1_SEQUENCE_END_ref'
analyze: INFO:         ASN1_ITEM_start(tname) \
analyze: INFO:         ^
analyze: INFO: /mnt/storage/gerazo/clang_asan/openssl/include/openssl/asn1t.h:36:40: note: expanded from macro 'ASN1_ITEM_start'
analyze: INFO:         OPENSSL_GLOBAL const ASN1_ITEM itname##_it = {
analyze: INFO:                                        ^
analyze: INFO: <scratch space>:140:1: note: expanded from here
analyze: INFO: PKCS7_RECIP_INFO_it
analyze: INFO: ^
analyze: INFO: In file included from /mnt/storage/gerazo/clang_asan/openssl/apps/pkcs7.c:14:
analyze: INFO: In file included from /mnt/storage/gerazo/clang_asan/openssl/apps/apps.h:22:
analyze: INFO: In file included from /mnt/storage/gerazo/clang_asan/openssl/include/openssl/x509.h:310:
analyze: INFO: /mnt/storage/gerazo/clang_asan/openssl/include/openssl/pkcs7.h:221:1: error: external variable 'PKCS7_ENC_CONTENT_it' defined in multiple translation units
analyze: INFO: DECLARE_ASN1_FUNCTIONS(PKCS7_ENC_CONTENT)
analyze: INFO: ^
analyze: INFO: /mnt/storage/gerazo/clang_asan/openssl/include/openssl/asn1.h:216:39: note: expanded from macro 'DECLARE_ASN1_FUNCTIONS'
analyze: INFO: # define DECLARE_ASN1_FUNCTIONS(type) DECLARE_ASN1_FUNCTIONS_name(type, type)
analyze: INFO:                                       ^
analyze: INFO: /mnt/storage/gerazo/clang_asan/openssl/include/openssl/asn1.h:223:9: note: expanded from macro 'DECLARE_ASN1_FUNCTIONS_name'
analyze: INFO:         DECLARE_ASN1_ENCODE_FUNCTIONS(type, name, name)
analyze: INFO:         ^
analyze: INFO: /mnt/storage/gerazo/clang_asan/openssl/include/openssl/asn1.h:232:9: note: expanded from macro 'DECLARE_ASN1_ENCODE_FUNCTIONS'
analyze: INFO:         DECLARE_ASN1_ITEM(itname)
analyze: INFO:         ^
analyze: INFO: /mnt/storage/gerazo/clang_asan/openssl/include/openssl/asn1.h:328:40: note: expanded from macro 'DECLARE_ASN1_ITEM'
analyze: INFO:         OPENSSL_EXTERN const ASN1_ITEM name##_it;
analyze: INFO:                                        ^
analyze: INFO: <scratch space>:152:1: note: expanded from here
analyze: INFO: PKCS7_ENC_CONTENT_it
analyze: INFO: ^
analyze: INFO: /mnt/storage/gerazo/clang_asan/openssl/crypto/pkcs7/pk7_asn1.c:148:3: note: also defined here
analyze: INFO: } ASN1_NDEF_SEQUENCE_END(PKCS7_ENC_CONTENT)
analyze: INFO:   ^
analyze: INFO: /mnt/storage/gerazo/clang_asan/openssl/include/openssl/asn1t.h:172:9: note: expanded from macro 'ASN1_NDEF_SEQUENCE_END'
analyze: INFO:         ASN1_ITEM_start(tname) \
analyze: INFO:         ^
analyze: INFO: /mnt/storage/gerazo/clang_asan/openssl/include/openssl/asn1t.h:36:40: note: expanded from macro 'ASN1_ITEM_start'
analyze: INFO:         OPENSSL_GLOBAL const ASN1_ITEM itname##_it = {
analyze: INFO:                                        ^
analyze: INFO: <scratch space>:160:1: note: expanded from here
analyze: INFO: PKCS7_ENC_CONTENT_it
analyze: INFO: ^
analyze: INFO: In file included from /mnt/storage/gerazo/clang_asan/openssl/apps/pkcs7.c:14:
analyze: INFO: In file included from /mnt/storage/gerazo/clang_asan/openssl/apps/apps.h:22:
analyze: INFO: In file included from /mnt/storage/gerazo/clang_asan/openssl/include/openssl/x509.h:310:
analyze: INFO: /mnt/storage/gerazo/clang_asan/openssl/include/openssl/pkcs7.h:218:1: error: external variable 'PKCS7_SIGNER_INFO_it' defined in multiple translation units
analyze: INFO: DECLARE_ASN1_FUNCTIONS(PKCS7_SIGNER_INFO)
analyze: INFO: ^
analyze: INFO: /mnt/storage/gerazo/clang_asan/openssl/include/openssl/asn1.h:216:39: note: expanded from macro 'DECLARE_ASN1_FUNCTIONS'
analyze: INFO: # define DECLARE_ASN1_FUNCTIONS(type) DECLARE_ASN1_FUNCTIONS_name(type, type)
analyze: INFO:                                       ^
analyze: INFO: /mnt/storage/gerazo/clang_asan/openssl/include/openssl/asn1.h:223:9: note: expanded from macro 'DECLARE_ASN1_FUNCTIONS_name'
analyze: INFO:         DECLARE_ASN1_ENCODE_FUNCTIONS(type, name, name)
analyze: INFO:         ^
analyze: INFO: /mnt/storage/gerazo/clang_asan/openssl/include/openssl/asn1.h:232:9: note: expanded from macro 'DECLARE_ASN1_ENCODE_FUNCTIONS'
analyze: INFO:         DECLARE_ASN1_ITEM(itname)
analyze: INFO:         ^
analyze: INFO: /mnt/storage/gerazo/clang_asan/openssl/include/openssl/asn1.h:328:40: note: expanded from macro 'DECLARE_ASN1_ITEM'
analyze: INFO:         OPENSSL_EXTERN const ASN1_ITEM name##_it;
analyze: INFO:                                        ^
analyze: INFO: <scratch space>:137:1: note: expanded from here
analyze: INFO: PKCS7_SIGNER_INFO_it
analyze: INFO: ^
analyze: INFO: /mnt/storage/gerazo/clang_asan/openssl/crypto/pkcs7/pk7_asn1.c:105:3: note: also defined here
analyze: INFO: } ASN1_SEQUENCE_END_cb(PKCS7_SIGNER_INFO, PKCS7_SIGNER_INFO)
analyze: INFO:   ^
analyze: INFO: /mnt/storage/gerazo/clang_asan/openssl/include/openssl/asn1t.h:199:46: note: expanded from macro 'ASN1_SEQUENCE_END_cb'
analyze: INFO: # define ASN1_SEQUENCE_END_cb(stname, tname) ASN1_SEQUENCE_END_ref(stname, tname)
analyze: INFO:                                              ^
analyze: INFO: /mnt/storage/gerazo/clang_asan/openssl/include/openssl/asn1t.h:204:9: note: expanded from macro 'ASN1_SEQUENCE_END_ref'
analyze: INFO:         ASN1_ITEM_start(tname) \
analyze: INFO:         ^
analyze: INFO: /mnt/storage/gerazo/clang_asan/openssl/include/openssl/asn1t.h:36:40: note: expanded from macro 'ASN1_ITEM_start'
analyze: INFO:         OPENSSL_GLOBAL const ASN1_ITEM itname##_it = {
analyze: INFO:                                        ^
analyze: INFO: <scratch space>:81:1: note: expanded from here
analyze: INFO: PKCS7_SIGNER_INFO_it
analyze: INFO: ^
analyze: INFO: Importing function _Z13ASN1_item_d2iPP13ASN1_VALUE_stPPKhlPK12ASN1_ITEM_st@x86_64 from /mnt/storage/gerazo/clang_asan/openssl/.xtu//ast/x86_64/mnt/storage/gerazo/clang_asan/openssl/crypto/asn1/tasn_dec.c.ast
analyze: INFO: Importing function _Z13ERR_put_erroriiiPKci@x86_64 from /mnt/storage/gerazo/clang_asan/openssl/.xtu//ast/x86_64/mnt/storage/gerazo/clang_asan/openssl/crypto/err/err.c.ast
analyze: INFO: Importing function _Z13ERR_get_statev@x86_64 from /mnt/storage/gerazo/clang_asan/openssl/.xtu//ast/x86_64/mnt/storage/gerazo/clang_asan/openssl/crypto/err/err.c.ast
analyze: INFO: Importing function _Z22CRYPTO_THREAD_run_oncePiPFvvE@x86_64 from /mnt/storage/gerazo/clang_asan/openssl/.xtu//ast/x86_64/mnt/storage/gerazo/clang_asan/openssl/crypto/threads_pthread.c.ast
analyze: INFO: Importing function _Z23CRYPTO_THREAD_get_localPj@x86_64 from /mnt/storage/gerazo/clang_asan/openssl/.xtu//ast/x86_64/mnt/storage/gerazo/clang_asan/openssl/crypto/threads_pthread.c.ast
analyze: INFO: Importing function _Z10BIO_printfP6bio_stPKcz@x86_64 from /mnt/storage/gerazo/clang_asan/openssl/.xtu//ast/x86_64/mnt/storage/gerazo/clang_asan/openssl/crypto/bio/b_print.c.ast
analyze: INFO: Importing function _Z16ERR_print_errorsP6bio_st@x86_64 from /mnt/storage/gerazo/clang_asan/openssl/.xtu//ast/x86_64/mnt/storage/gerazo/clang_asan/openssl/crypto/err/err_prn.c.ast
analyze: INFO: Importing function _Z28CRYPTO_THREAD_get_current_idv@x86_64 from /mnt/storage/gerazo/clang_asan/openssl/.xtu//ast/x86_64/mnt/storage/gerazo/clang_asan/openssl/crypto/threads_pthread.c.ast
analyze: INFO: Importing function _Z23ERR_get_error_line_dataPPKcPiS1_S2_@x86_64 from /mnt/storage/gerazo/clang_asan/openssl/.xtu//ast/x86_64/mnt/storage/gerazo/clang_asan/openssl/crypto/err/err.c.ast
analyze: INFO: Importing function _Z10PKCS7_freeP8pkcs7_st@x86_64 from /mnt/storage/gerazo/clang_asan/openssl/.xtu//ast/x86_64/mnt/storage/gerazo/clang_asan/openssl/crypto/pkcs7/pk7_asn1.c.ast
analyze: INFO: Importing function _Z14ASN1_item_freeP13ASN1_VALUE_stPK12ASN1_ITEM_st@x86_64 from /mnt/storage/gerazo/clang_asan/openssl/.xtu//ast/x86_64/mnt/storage/gerazo/clang_asan/openssl/crypto/asn1/tasn_fre.c.ast
analyze: INFO: Importing function _Z22asn1_string_embed_freeP14asn1_string_sti@x86_64 from /mnt/storage/gerazo/clang_asan/openssl/.xtu//ast/x86_64/mnt/storage/gerazo/clang_asan/openssl/crypto/asn1/asn1_lib.c.ast
analyze: INFO: Importing function _Z14release_engineP9engine_st@x86_64 from /mnt/storage/gerazo/clang_asan/openssl/.xtu//ast/x86_64/mnt/storage/gerazo/clang_asan/openssl/apps/apps.c.ast
analyze: INFO: Importing function _Z8BIO_freeP6bio_st@x86_64 from /mnt/storage/gerazo/clang_asan/openssl/.xtu//ast/x86_64/mnt/storage/gerazo/clang_asan/openssl/crypto/bio/bio_lib.c.ast
analyze: INFO: Importing function _Z19CRYPTO_free_ex_dataiPvP17crypto_ex_data_st@x86_64 from /mnt/storage/gerazo/clang_asan/openssl/.xtu//ast/x86_64/mnt/storage/gerazo/clang_asan/openssl/crypto/ex_data.c.ast
analyze: INFO: Importing function _Z24CRYPTO_THREAD_write_lockPv@x86_64 from /mnt/storage/gerazo/clang_asan/openssl/.xtu//ast/x86_64/mnt/storage/gerazo/clang_asan/openssl/crypto/threads_pthread.c.ast
analyze: INFO: Importing function _Z14OPENSSL_sk_numPK8stack_st@x86_64 from /mnt/storage/gerazo/clang_asan/openssl/.xtu//ast/x86_64/mnt/storage/gerazo/clang_asan/openssl/crypto/stack/stack.c.ast
analyze: INFO: Importing function _Z20CRYPTO_THREAD_unlockPv@x86_64 from /mnt/storage/gerazo/clang_asan/openssl/.xtu//ast/x86_64/mnt/storage/gerazo/clang_asan/openssl/crypto/threads_pthread.c.ast
analyze: INFO: Importing function _Z15OPENSSL_sk_freeP8stack_st@x86_64 from /mnt/storage/gerazo/clang_asan/openssl/.xtu//ast/x86_64/mnt/storage/gerazo/clang_asan/openssl/crypto/stack/stack.c.ast
analyze: INFO: Importing function _Z23CRYPTO_THREAD_lock_freePv@x86_64 from /mnt/storage/gerazo/clang_asan/openssl/.xtu//ast/x86_64/mnt/storage/gerazo/clang_asan/openssl/crypto/threads_pthread.c.ast
analyze: INFO: Importing function _Z12BIO_free_allP6bio_st@x86_64 from /mnt/storage/gerazo/clang_asan/openssl/.xtu//ast/x86_64/mnt/storage/gerazo/clang_asan/openssl/crypto/bio/bio_lib.c.ast
analyze: INFO: Importing function _Z13CRYPTO_mallocmPKci@x86_64 from /mnt/storage/gerazo/clang_asan/openssl/.xtu//ast/x86_64/mnt/storage/gerazo/clang_asan/openssl/crypto/mem.c.ast
analyze: INFO: Importing function _Z16OPENSSL_sk_valuePK8stack_sti@x86_64 from /mnt/storage/gerazo/clang_asan/openssl/.xtu//ast/x86_64/mnt/storage/gerazo/clang_asan/openssl/crypto/stack/stack.c.ast
analyze: INFO: Importing function _Z18CRYPTO_get_ex_dataPK17crypto_ex_data_sti@x86_64 from /mnt/storage/gerazo/clang_asan/openssl/.xtu//ast/x86_64/mnt/storage/gerazo/clang_asan/openssl/crypto/ex_data.c.ast
analyze: INFO: Importing function _Z16ASN1_OBJECT_freeP14asn1_object_st@x86_64 from /mnt/storage/gerazo/clang_asan/openssl/.xtu//ast/x86_64/mnt/storage/gerazo/clang_asan/openssl/crypto/asn1/a_object.c.ast
analyze: INFO: _Z10pkcs7_mainiPPc@x86_64 has_work_wl not_exhausted no_block_aborted
analyze: INFO: ===-------------------------------------------------------------------------===
analyze: INFO:                          Miscellaneous Ungrouped Timers
analyze: INFO: ===-------------------------------------------------------------------------===
analyze: INFO: 
analyze: INFO:    ---User Time---   --System Time--   --User+System--   ---Wall Time---  --- Name ---
analyze: INFO:    8.2480 (100.0%)   0.5840 (100.0%)   8.8320 (100.0%)  19.4688 (100.0%)  Analyzer Total Time
analyze: INFO:    8.2480 (100.0%)   0.5840 (100.0%)   8.8320 (100.0%)  19.4688 (100.0%)  Total
analyze: INFO: 
analyze: INFO: ===-------------------------------------------------------------------------===
analyze: INFO:                           ... Statistics Collected ...
analyze: INFO: ===-------------------------------------------------------------------------===
analyze: INFO: 
analyze: INFO:   1469 ASTContext       - The # of getXTUDefinition function called
analyze: INFO:     35 ASTContext       - The # of getXTUDefinition successfully return the requested function's body
analyze: INFO:   1434 ASTContext       - The # of getXTUDefinition called but the function is not in other TU
analyze: INFO:     71 AnalysisConsumer - The maximum number of basic blocks in a function.
analyze: INFO:    525 AnalysisConsumer - The # of basic blocks in the analyzed functions.
analyze: INFO:   1228 AnalysisConsumer - The # of functions at top level.
analyze: INFO:      1 AnalysisConsumer - The # of functions and blocks analyzed (as top level with inlining turned on).
analyze: INFO:     52 AnalysisConsumer - The % of reachable basic blocks.
analyze: INFO:    146 CoreEngine       - The # of paths explored by the analyzer.
analyze: INFO:      1 CoreEngine       - The # of times we reached the max number of steps.
analyze: INFO: 150000 CoreEngine       - The # of steps executed.
analyze: INFO:   3166 ExprEngine       - The # of times we inlined a call
analyze: INFO:     93 ExprEngine       - The # of times we reached inline count maximum
analyze: INFO:  32007 ExprEngine       - The # of times RemoveDeadBindings is called
analyze: INFO:      2 ExprEngine       - The # of times we re-evaluated a call without inlining
analyze: INFO: 
analyze: INFO: 4 errors generated.

**Comment by martong** [comment]
@gerazo Is this still an issue?

**Comment by martong** [comment]
Outdated.
